### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by vyas45** [chishui/terminal-leetcode#19]
Is it enough to have the config file for login ?  I don't seem to be getting logged in. 

Step1: Setup the config file with the username and password. 
Step2: launch the program

Any other way to debug it ? Does it matter if i have login through google ? Do you support that ?

**Comment by chishui** [comment]
If you use Google account to log into leetcode.com, then this is not supported currently.

**Comment by vyas45** [comment]
Got it ! Will try if I can add that support and contribute back :)

**Comment by chishui** [comment]
Yes, please, you're very welcome to contribute!

**Comment by alphab1t** [comment]
Hello,
Commenting on this thread because I am also experiencing an issue related to login. I am not using google account. I have created the config.cfg file, yet it fails with the backtrace below. Please let me know if I need open a new issue.

ERROR:leetcode.auth:Network error: url: https://leetcode.com/api/problems/algorithms/ code: 0
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.macosx-10.12-intel/egg/leetcode/terminal.py", line 194, in run_retrieve_home
    self.leetcode.is_login = auth.is_login()
  File "build/bdist.macosx-10.12-intel/egg/leetcode/auth.py", line 66, in is_login
    r = retrieve(API_URL, headers=headers)
  File "build/bdist.macosx-10.12-intel/egg/leetcode/auth.py", line 82, in retrieve
    raise NetworkError('Network error: url: %s' % url)
NetworkError

**Comment by astrokjw** [comment]
I have the same problem with @alphab1t .
Any updates?
