### ISSUE TITLE
error from urwid

### ISSUE THREAD

**Issue by haomen** [chishui/terminal-leetcode#38]
Following installation as:
sudo apt-get install libxml2-dev libxslt1-dev python-dev
sudo pip install urwid
sudo pip install terminal-leetcode

setup leetcode config in ~/.config/leetcode/config.cfg
then "leetcode"
saw error msg as follows, i can replicated this error on debian 9, ubuntu14.04 and 16.04, seems not because of my linux env settings.  

ERROR:leetcode.terminal:Fatal error in main loop
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/leetcode/terminal.py", line 262, in run
    self.loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid-2.0.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/urwid-2.0.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/local/lib/python2.7/dist-packages/urwid-2.0.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/usr/local/lib/python2.7/dist-packages/urwid-2.0.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 821, in _loop
    alarm_callback()
  File "/usr/local/lib/python2.7/dist-packages/urwid-2.0.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 172, in cb
    callback(self, user_data)
  File "/usr/local/lib/python2.7/dist-packages/leetcode/views/viewhelper.py", line 3, in refresh
    loop.draw_screen()
  File "/usr/local/lib/python2.7/dist-packages/urwid-2.0.1-py2.7-linux-x86_64.egg/urwid/main_loop.py", line 586, in draw_screen
    canvas = self._topmost_widget.render(self.screen_size, focus=True)
  File "/usr/local/lib/python2.7/dist-packages/urwid-2.0.1-py2.7-linux-x86_64.egg/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid-2.0.1-py2.7-linux-x86_64.egg/urwid/container.py", line 1086, in render
    focus and self.focus_part == 'body')
  File "/usr/local/lib/python2.7/dist-packages/urwid-2.0.1-py2.7-linux-x86_64.egg/urwid/widget.py", line 144, in cached_render
    canv = fn(self, size, focus=focus)
  File "/usr/local/lib/python2.7/dist-packages/urwid-2.0.1-py2.7-linux-x86_64.egg/urwid/container.py", line 778, in render
    bottom_c = self.bottom_w.render(size)
AttributeError: 'NoneType' object has no attribute 'render'

**Comment by shuaiyu8** [comment]
I have the same problem, too.

**Comment by mrundle** [comment]
neodooth's patch fixed the issue for me btw

**Comment by astrokjw** [comment]
I have the same issue.
uname -a               
Linux localhost 3.18.71-14977309 #1 SMP PREEMPT Tue Dec 11 20:05:56 KST 2018 aarch64 Android

**Comment by chishui** [comment]
I should have fixed this issue, please check
